/* Progressive enhancement: essential content and navigation work without JS. */
(() => {
 const header=document.querySelector('.s-header');
 const nav=document.querySelector('.s-nav');
 const menu=document.querySelector('.s-menu');
 const closeMenu=(focus=false)=>{nav?.classList.remove('is-open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Open navigation');if(focus)menu?.focus();};
 menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('is-open',open);});
 nav?.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav?.classList.contains('is-open'))closeMenu(true);});
 document.addEventListener('click',event=>{if(header&&!header.contains(event.target))closeMenu();});
 const scrollHeader=()=>header?.classList.toggle('is-scrolled',window.scrollY>40);
 window.addEventListener('scroll',scrollHeader,{passive:true});scrollHeader();
 document.querySelectorAll('[data-studio-year]').forEach(el=>el.textContent=new Date().getFullYear());
 if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('.s-nav a').forEach(a=>{if(a.hash==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}}),{rootMargin:'-20% 0px -50% 0px'});document.querySelectorAll('#services,#work,#approach,#training,#quiz').forEach(el=>observer.observe(el));}
 if(document.body.classList.contains('studio-site')){const aliases={'#confidence-challenge':'quiz','#how-it-works':'approach','#audience-paths':'training'};if(aliases[location.hash]){const id=aliases[location.hash];history.replaceState(null,'','#'+id);document.getElementById(id)?.scrollIntoView();}}
 const roles={executives:['LEAD WITH CLARITY','Better questions.<br>More confident leadership.','Data literacy, decision intelligence, AI for leaders and analytics strategy. Understand the evidence before you make the call.','executive','executive'],business:['PUT KNOWLEDGE TO WORK','Everyday data.<br>Real-world confidence.','Analytics fundamentals, storytelling, AI prompting and Copilot. Build practical skills around the decisions you make every day.','business','business'],analysts:['BUILD WITH PURPOSE','Technical depth.<br>Human-centred design.','Power BI, Microsoft Fabric, modelling, visual design and advanced analytics. Connect strong foundations to reports people can act on.','powerbi','analytics']};
 document.querySelectorAll('[data-role]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const r=roles[button.dataset.role];const panel=document.getElementById('training-panel');panel.innerHTML=`<span class="s-number">${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><a class="s-button" href="organisations.html?recommend=${r[3]}#programmes">Explore ${r[4]} training <span aria-hidden="true">↗</span></a>`;}));
 const app=document.getElementById('quiz-app');if(!app)return;
 const questions=[{title:'What would you like to improve?',options:[['reporting','Reporting & insight'],['platform','Your data platform'],['ai','AI adoption'],['training','Team capability'],['strategy','Executive decisions'],['design','Dashboard design']]},{title:'Who are we helping?',options:[['leaders','Executives & leaders'],['business','Business professionals'],['analysts','Analytics professionals'],['mixed','A mixed team']]},{title:'Where are you starting?',options:[['explore','Exploring the possibilities'],['improve','Improving something existing'],['build','Ready to build or learn']]}];
 const paths={reporting:['Power BI & Microsoft Fabric','analytics','Bring your reporting into one clear, trusted view. Start with the business questions and shape the model and dashboard around them.'],platform:['Power BI & Microsoft Fabric','analytics','Build a dependable foundation for your analytics. Review architecture, data flows and ownership before choosing the next platform step.'],ai:['AI & Automation','ai','Find a useful, manageable AI application. Start with a real workflow, a clear outcome and human checks.'],training:['Training & Enablement','enablement','Build confidence through focused learning and guided practice, matched to the work your team actually does.'],strategy:['Strategy & Advisory','strategy','Turn business priorities into a practical analytics roadmap. Clarify the decisions, assess maturity and agree the first useful step.'],design:['Power BI & Dashboard Design','analytics','Make the signal easier to see. Review your dashboard around its audience, decision context and visual hierarchy.']};
 let step=0;let answers=[null,null,null];
 const focusHeading=()=>{const target=app.querySelector('legend,h3');if(target){target.tabIndex=-1;target.focus({preventScroll:true});}};
 function render(moveFocus=false){const q=questions[step];app.innerHTML=`<div class="s-quiz-progress"><span>YOUR NEXT CHAPTER</span><span>0${step+1} / 03</span></div><div class="s-progress-track" aria-hidden="true"><i style="width:${(step+1)/3*100}%"></i></div><form><fieldset><legend>${q.title}</legend><div class="s-quiz-options">${q.options.map(([value,label])=>`<label class="s-quiz-option"><input type="radio" name="answer" value="${value}" ${answers[step]===value?'checked':''}><span>${label}</span></label>`).join('')}</div></fieldset><div class="s-quiz-status" role="status">${answers[step]?'Selection saved. Continue when you’re ready.':'Choose one answer to continue.'}</div><div class="s-quiz-controls"><button type="button" class="s-quiz-back" ${step===0?'disabled':''}>← Back</button><button class="s-button" type="submit" ${answers[step]?'':'disabled'}>${step===2?'Show my pathway':'Continue'} <span aria-hidden="true">→</span></button></div></form>`;
 app.querySelector('form').addEventListener('change',event=>{answers[step]=event.target.value;app.querySelector('[type=submit]').disabled=false;app.querySelector('[role=status]').textContent='Selection saved. Continue when you’re ready.';});
 app.querySelector('.s-quiz-back').addEventListener('click',()=>{if(step>0){step--;render(true);}});
 app.querySelector('form').addEventListener('submit',event=>{event.preventDefault();if(!answers[step])return;if(step<2){step++;render(true);}else result();});
 if(moveFocus)focusHeading();}
 function result(){const [goal,audience,readiness]=answers;const p=paths[goal];const labels=answers.map((a,i)=>questions[i].options.find(o=>o[0]===a)[1]);const next={explore:'Start with a focused discovery conversation to clarify the opportunity.',improve:'Bring an existing report, workflow or learning challenge. We can assess what to improve first.',build:'Define a focused first scope, the people involved and a useful outcome to work towards.'}[readiness];const audienceCopy={leaders:'For leaders: connect the work to business priorities and confident decisions.',business:'For business professionals: focus on practical workflows and clear, usable information.',analysts:'For analytics professionals: combine technical foundations with thoughtful design.',mixed:'For a mixed team: align the decision-makers, users and people building the solution.'}[audience];let detail=`services.html#${p[1]}`;if(goal==='training')detail=audience==='analysts'?'organisations.html?recommend=powerbi#tools':audience==='leaders'?'organisations.html?recommend=executive#programmes':audience==='business'?'organisations.html?recommend=business#programmes':'organisations.html#programmes';const body=`Hello NotABot Studio,\n\nMy recommended pathway: ${p[0]}\nMy goal: ${labels[0]}\nAudience: ${labels[1]}\nStarting point: ${labels[2]}\n\nHere is a little more about what I need:\n`;const email=`mailto:hello@notabot.studio?subject=${encodeURIComponent('My NotABot pathway: '+p[0])}&body=${encodeURIComponent(body)}`;
 app.innerHTML=`<div class="s-quiz-result s-enter"><div class="s-kicker">YOUR RECOMMENDED PATHWAY</div><h3>${p[0]}</h3><p>${p[2]}</p><p>${audienceCopy}</p><p><strong>Your first step</strong><br>${next}</p><a class="s-button" href="${email}">Discuss this pathway <span aria-hidden="true">↗</span></a><p class="s-small">Opens an email draft for you to review and send.</p><a class="s-text-link" href="${detail}">Explore this pathway →</a><div class="s-quiz-controls"><button class="s-quiz-back" id="quiz-edit" type="button">← Edit answers</button><button class="s-quiz-back" id="quiz-reset" type="button">Start again ↻</button></div></div>`;
 app.querySelector('#quiz-edit').addEventListener('click',()=>{step=2;render(true);});app.querySelector('#quiz-reset').addEventListener('click',()=>{step=0;answers=[null,null,null];render(true);});focusHeading();}
 render();
})();

// Build an email draft locally; no form data is transmitted by this page.
(()=>{const form=document.getElementById('studio-enquiry');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const body='Hello NotABot Studio,\n\n'+data.get('message')+'\n\nName: '+data.get('name')+'\nEmail: '+data.get('email')+'\nInterest: '+data.get('service');const result=document.getElementById('enquiry-result');result.replaceChildren();const note=document.createElement('p');note.textContent='Your draft is ready. Open it in your email app to review and send.';const link=document.createElement('a');link.className='s-button';link.textContent='Open my email draft ↗';link.href='mailto:hello@notabot.studio?subject='+encodeURIComponent('Website enquiry: '+data.get('service'))+'&body='+encodeURIComponent(body);result.append(note,link);link.focus();});})();
