(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.NotabotUX=api;})(typeof window==='object'?window:this,function(){
 const choices={context:['personal','organisation','unknown'],goal:['information','reports','ai','unknown'],obstacle:['skills','delivery','both','unknown']};
 const routes={home:'index.html',training:'training.html',individual:'individuals.html',organisation:'organisations.html',consultancy:'services.html',about:'about.html',approach:'approach.html',estimate:'plan.html',project:'fleet.html',guide:'start.html'};
 function clean(a={}){if(!a||typeof a!=='object')a={};const out={};for(const k of Object.keys(choices))if(choices[k].includes(a[k]))out[k]=a[k];if(!out.context||out.context==='unknown'){delete out.goal;delete out.obstacle;}if(!out.goal||out.goal==='unknown')delete out.obstacle;return out;}
 function next(a){a=clean(a);return !a.context?'context':a.context==='unknown'?'result':!a.goal?'goal':a.goal==='unknown'?'result':!a.obstacle?'obstacle':'result';}
 function classify(a){a=clean(a);if(next(a)!=='result')return null;const result=(type,title,reason,href,label)=>({type,title,reason,href,label});
 if(a.context==='unknown')return result('exploration','Explore at your own pace','You do not need to name your need yet. See what NotABot does, then choose a route that feels useful.','about.html','Get to know NotABot');
 if(a.goal==='unknown')return result('human','Start with a conversation','A conversation can help clarify the outcome before choosing training or delivery support.','contact.html?topic=guidance&from=guide','Talk to NotABot');
 if(a.context==='personal'){
 if(a.obstacle==='skills')return result('training','Start with individual learning','You want to build your own confidence or skills. Individual learning is the relevant route; you do not need an employer to enquire.',a.goal==='ai'?'individuals.html#ai-learning':a.goal==='reports'?'individuals.html#course-visualisation':'individuals.html#course-analytics',a.goal==='ai'?'Discuss individual AI learning':'Explore individual learning');
 if(a.obstacle==='unknown')return result('exploration','Explore individual learning','You know your goal but are still identifying what gets in the way. Review the course outcomes or talk it through.','individuals.html','Browse individual learning');
 return result('human','Talk through the practical problem','You need help with delivery or a mix of support for your own work. A conversation can establish what would fit.','contact.html?topic=guidance&from=guide','Discuss my situation');}
 if(a.obstacle==='skills')return result('training','Start with team training','Your main need is capability. Explore learning outcomes for your people before discussing a programme.','organisations.html#programmes','Explore team training');
 if(a.obstacle==='delivery')return result('consultancy','Explore Consultancy','You need something to work better. Practical delivery support is a useful starting point for discussing scope.','services.html#'+({information:'strategy',reports:'analytics',ai:'ai'}[a.goal]),'Explore relevant consultancy');
 if(a.obstacle==='both')return result('combined','Connect Training + Consultancy','Your challenge includes both practical delivery and people’s capability. Discuss those needs together.','organisations.html#combined','Explore combined support');
 return result('human','Clarify the need together','You have an organisational goal but the obstacle is not clear yet. Talk it through before deciding on a service.','contact.html?topic=guidance&from=guide','Talk to NotABot');}
 function estimate(data,key,count,delivery){const n=Number(count),p=data[key];if(!p||!['balanced','protect'].includes(delivery))throw Error('Choose a listed programme and delivery option.');if(String(count).trim()===''||!Number.isInteger(n)||n<4||n>40)throw Error('Enter a whole number from 4 to 40. For a different group size, contact us.');const cap=delivery==='protect'?p.protectCapacity:p.capacity,cohorts=Math.ceil(n/cap),sizes=Array.from({length:cohorts},(_,i)=>Math.floor(n/cohorts)+(i<n%cohorts?1:0));return {n,cohorts,sizes,maxAway:Math.max(...sizes),price:p.basePrice+(cohorts-1)*p.additionalCohort,format:p.format,name:p.name};}
 return {choices,routes,clean,next,classify,estimate};
});

