(()=>{'use strict';
 const $=s=>document.querySelector(s), C=window.NotabotUX,D=window.NotabotCatalogue,params=new URLSearchParams(location.search);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const header=$('.ux-header'),menu=$('.ux-menu'),nav=$('#ux-nav');
 if(menu){menu.hidden=false;header.classList.add('js-nav');const close=()=>{nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false');};menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open));});header.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){close();menu.focus();}});nav.addEventListener('click',e=>{if(e.target.closest('a'))close();});const media=matchMedia('(max-width:700px)');media.addEventListener('change',()=>{if(media.matches&&nav.contains(document.activeElement)){close();menu.focus();}});}
 document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
 if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/')){const aliases={'#quiz':'start.html','#confidence-challenge':'start.html','#training':'training.html','#approach':'approach.html','#how-it-works':'approach.html','#contact':'contact.html','#services':'services.html','#work':'fleet.html','#audience-paths':'organisations.html'};if(aliases[location.hash])location.replace(aliases[location.hash]);}
 if(!C)return;
 const labels={context:{personal:'For myself',organisation:'For my organisation',unknown:'I am exploring / not sure'},goal:{information:'Understand information and make better decisions',reports:'Improve reports or explain information clearly',ai:'Use AI or automate repetitive work',unknown:'I am not sure what the goal is yet'},obstacle:{skills:'Skills or confidence',delivery:'Something needs to be built or fixed',both:'Both skills and practical delivery',unknown:'I am not sure what is getting in the way'}};
 const storageKey='notabot-guidance-v1';
 function save(a){try{sessionStorage.setItem(storageKey,JSON.stringify(C.clean(a)));}catch{}}
 function saved(){try{return C.clean(JSON.parse(sessionStorage.getItem(storageKey)||'{}'));}catch{return {};}}
 const guide=$('#ux-guide');
 if(guide){let answers=saved(),step='context',depth=0;const steps=['context','goal','obstacle','result'];const validStep=(s,a)=>{const n=C.next(a);return steps.includes(s)&&steps.indexOf(s)<=steps.indexOf(n)?s:n;};
 if(C.choices.context.includes(params.get('context'))){answers=answers.context===params.get('context')?answers:{context:params.get('context')};}
 if(history.state?.notabot){answers=C.clean(history.state.answers);step=validStep(history.state.step,answers);depth=history.state.depth||0;}else if(location.hash){step=validStep(location.hash.slice(1),answers);}else if(!params.has('context')&&Object.keys(answers).length)step=C.next(answers);
 const backRoute=C.routes[params.get('from')]||'index.html';$('#ux-guide-return').href=backRoute;
 function stamp(replace=false){const state={notabot:true,answers,step,depth};history[replace?'replaceState':'pushState'](state,'','#'+step);save(answers);}
 function go(s,replace=false){step=validStep(s,answers);if(!replace)depth++;stamp(replace);render(true);}
 function render(focus=false){guide.hidden=false;const progress=`<ol class="ux-progress" aria-label="Guidance progress">${['Who needs help','Your goal','What gets in the way','Starting point'].map((t,i)=>`<li${steps[i]===step?' aria-current="step"':''}>${i+1}. ${t}</li>`).join('')}</ol>`;
 if(step==='result'){const r=C.classify(answers);if(!r){go(C.next(answers),true);return;}guide.innerHTML=progress+`<p class="ux-eyebrow ux-result-type">Suggested starting point</p><h2 tabindex="-1" id="guide-title">${escape(r.title)}</h2><p>${escape(r.reason)}</p><h3>Based on your answers</h3><ul class="ux-summary">${Object.entries(answers).map(([k,v])=>`<li>${escape(labels[k][v])} <button class="ux-secondary" type="button" data-edit="${k}">Change</button></li>`).join('')}</ul><p class="ux-note">This is a starting suggestion, not a diagnosis, quote or commitment.</p><div class="ux-actions"><a class="ux-button" href="${escape(r.href)}">${escape(r.label)} ↗</a><button type="button" class="ux-secondary" id="guide-reset">Start again</button></div><details><summary>Explore another route</summary><div class="ux-actions"><a href="individuals.html">Individual learning</a><a href="organisations.html">Organisation support</a><a href="services.html">Consultancy</a><a href="contact.html?topic=guidance&from=guide">Talk to NotABot</a></div></details>`;
 guide.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.edit)));$('#guide-reset').addEventListener('click',()=>{answers={};depth=0;go('context',true);});
 }else{const title={context:'Who are you looking to help?',goal:'What would you like to achieve?',obstacle:'What is getting in the way?'}[step];guide.innerHTML=progress+`<form id="guide-form"><fieldset class="ux-guide-question"><legend tabindex="-1" id="guide-title">${title}</legend>${Object.entries(labels[step]).map(([k,v])=>`<label class="ux-option"><input type="radio" name="answer" value="${k}"${answers[step]===k?' checked':''}><span>${v}</span></label>`).join('')}</fieldset><p id="guide-error" class="ux-field-error" role="alert"></p><p id="guide-update" role="status" class="ux-status"></p><div class="ux-guide-controls">${step!=='context'?'<button type="button" class="ux-secondary" id="guide-back">Back</button>':''}<button class="ux-button" type="submit">Continue →</button></div></form>`;
 $('#guide-form').addEventListener('change',e=>{const old=answers[step];answers[step]=e.target.value;if(old!==e.target.value){if(step==='context'){delete answers.goal;delete answers.obstacle;}if(step==='goal')delete answers.obstacle;$('#guide-update').textContent='Answer saved. Later answers will be checked again.';}answers=C.clean(answers);stamp(true);$('#guide-error').textContent='';});
 $('#guide-form').addEventListener('submit',e=>{e.preventDefault();if(!answers[step]){$('#guide-error').textContent='Choose an answer to continue, or use an exploration link below.';guide.querySelector('input').focus();return;}const target=step==='context'?(answers.context==='unknown'?'result':'goal'):step==='goal'?(answers.goal==='unknown'?'result':'obstacle'):'result';go(target);});
 $('#guide-back')?.addEventListener('click',()=>{if(depth>0)history.back();else go(step==='obstacle'?'goal':'context',true);});}
 if(focus)$('#guide-title').focus();}
 stamp(true);render();addEventListener('popstate',e=>{if(e.state?.notabot){answers=C.clean(e.state.answers);step=validStep(e.state.step,answers);depth=e.state.depth||0;save(answers);render(true);}});
 }
 function topic(){const raw=params.get('topic')||'',parts=raw.split(':');if(parts[0]==='course'&&D.individual[parts[1]])return 'Individual learning: '+D.individual[parts[1]].name;if(parts[0]==='team'&&D.programmes[parts[1]])return 'Team training: '+D.programmes[parts[1]].name;const topics={training:'Training',organisation:'Organisation support',consultancy:'Consultancy',combined:'Training + Consultancy',strategy:'Strategy & Advisory',analytics:'Reporting, Power BI & Microsoft Fabric',ai:'AI & Automation','individual-ai':'Individual AI learning',experience:'Relevant experience',approach:'Our approach',fleet:'A fleet reporting challenge',estimate:'Training estimate',guidance:'Guidance'};return topics[raw]||'';}
 const contact=$('#ux-contact');if(contact){contact.hidden=false;let context=topic();if(params.get('topic')==='guidance'){const a=saved();context='Guidance: '+Object.entries(a).map(([k,v])=>labels[k][v]).join(' / ');}
 if(params.get('programme'))try{const r=C.estimate(D.programmes,params.get('programme'),params.get('count'),params.get('delivery'));context=`Team estimate: ${r.name}; ${r.n} people; ${params.get('delivery')==='protect'?'smaller':'standard'} groups; indicative R${r.price}.`;}catch{}
 $('#context').value=context;const back=C.routes[params.get('from')];if(back){$('#contact-return').href=back;
 if(params.get('from')==='individual'&&params.get('topic')?.startsWith('course:')){const k=params.get('topic').slice(7);if(Object.hasOwn(D.individual,k))$('#contact-return').href=back+'#course-'+k;}
 if(params.get('from')==='organisation'&&params.get('topic')?.startsWith('team:')){const k=params.get('topic').slice(5);if(Object.hasOwn(D.programmes,k))$('#contact-return').href=back+'#programme-'+k;}
 if(params.get('from')==='estimate'&&params.get('programme'))try{C.estimate(D.programmes,params.get('programme'),params.get('count'),params.get('delivery'));$('#contact-return').href=back+'?'+new URLSearchParams({programme:params.get('programme'),count:params.get('count'),delivery:params.get('delivery')});}catch{}
 $('#contact-return').textContent='Return to '+({individual:'individual learning',organisation:'organisation support',guide:'my guidance',estimate:'the estimate',project:'the project'}[params.get('from')]||params.get('from'));}
 contact.addEventListener('submit',e=>{e.preventDefault();const errors=[];for(const id of ['name','email','message']){const input=$('#'+id);const message=!input.value.trim()?`Enter your ${id==='message'?'question or message':id}.`:id==='email'&&!input.validity.valid?'Enter a valid email address.':'';input.setAttribute('aria-invalid',String(!!message));$('#'+id+'-error').hidden=!message;$('#'+id+'-error').textContent=message;if(message)errors.push({id,message});}const summary=$('#contact-errors');summary.hidden=!errors.length;if(errors.length){$('#ux-draft').hidden=true;summary.innerHTML='<p>Please check the following:</p>'+errors.map(e=>`<a href="#${e.id}">${e.message}</a>`).join('');summary.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>$(a.getAttribute('href')).focus()));summary.focus();return;}
 const text=`Hello NotABot,\n\n${$('#message').value.trim()}\n\nName: ${$('#name').value.trim()}\nEmail: ${$('#email').value.trim()}${$('#organisation').value.trim()?'\nOrganisation: '+$('#organisation').value.trim():''}${$('#context').value.trim()?'\nContext: '+$('#context').value.trim():''}`;$('#draft-text').value=text;$('#draft-open').href='mailto:hello@notabot.studio?subject='+encodeURIComponent('NotABot enquiry')+'&body='+encodeURIComponent(text);$('#ux-draft').hidden=false;$('#draft-status').textContent='';$('#draft-title').focus();});
 contact.addEventListener('input',()=>{$('#ux-draft').hidden=true;});$('#draft-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#draft-text').value);$('#draft-status').textContent='Copied. Paste into your email app when you are ready to send.';}catch{$('#draft-text').focus();$('#draft-text').select();$('#draft-status').textContent='Select and copy the draft above using your device’s copy command.';}});
 }
 const estimator=$('#ux-estimate');if(estimator){estimator.hidden=false;const output=$('#estimate-result');if(Object.hasOwn(D.programmes,params.get('programme')))$('#programme').value=params.get('programme');if(params.has('count'))$('#participants').value=params.get('count');if(['balanced','protect'].includes(params.get('delivery')))estimator.querySelector('[value="'+params.get('delivery')+'"]').checked=true;const live=document.createElement('p');live.setAttribute('role','status');live.className='ux-note';estimator.append(live);
 function calculate(focus=false){const key=$('#programme').value,count=$('#participants').value,delivery=estimator.querySelector('[name=delivery]:checked').value;try{const r=C.estimate(D.programmes,key,count,delivery);$('#participants').setAttribute('aria-invalid','false');$('#participants-error').hidden=true;output.hidden=false;const money='R'+r.price.toLocaleString('en-ZA');output.innerHTML=`<p class="ux-eyebrow">Indicative training estimate</p><h2 id="estimate-title">${escape(r.name)}</h2><p class="ux-estimate-value">${money}</p><dl class="ux-facts"><div><dt>People / groups</dt><dd>${r.n} people in ${r.cohorts} group${r.cohorts===1?'':'s'} (${r.sizes.join(' + ')})</dd></div><div><dt>Maximum attending one group</dt><dd>${r.maxAway} people</dd></div><div><dt>Programme format per group</dt><dd>${escape(r.format)}</dd></div></dl><p class="ux-note">Assumes groups run separately. This is the programme cohort fee only. Optional additional scope, travel, venue and taxes are subject to confirmation. Dates, delivery arrangements and current pricing must be agreed before booking.</p><a class="ux-button" href="contact.html?topic=estimate&from=estimate&programme=${key}&count=${r.n}&delivery=${delivery}">Discuss this estimate ↗</a>`;live.textContent=`Estimate updated: ${money}, ${r.cohorts} groups.`;}catch(e){output.hidden=true;$('#participants-error').textContent=e.message;$('#participants-error').hidden=false;$('#participants').setAttribute('aria-invalid','true');live.textContent='Estimate unavailable. Check the number of people.';if(focus)$('#participants').focus();}}
 estimator.addEventListener('submit',e=>{e.preventDefault();calculate(true);});estimator.addEventListener('change',()=>calculate());calculate();}
})();


